name: Lifesteal
version: '1.0-SNAPSHOT'
main: io.github.rainpaw.lifesteal.Lifesteal
api-version: '1.21'
authors: [rainpaw10]
description: A Lifesteal plugin copy aimed at using the real Lifesteal recipes while adding some QoL features.
website: rainpaw.github.io
commands:
  withdraw:
    description: Withdraws a specified amount of hearts from the player.
    usage: /<command> [amount]